# Generated by Django 4.2.7 on 2023-11-18 23:18

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wavevalue',
            name='point',
        ),
        migrations.AddField(
            model_name='wavepoint',
            name='time',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wavepoint',
            name='x',
            field=models.FloatField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wavepoint',
            name='y',
            field=models.FloatField(default=datetime.datetime(2023, 11, 18, 23, 18, 21, 627077, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='WaveTime',
        ),
        migrations.DeleteModel(
            name='WaveValue',
        ),
    ]
